### ISSUE TITLE
Host OS Updates

### ISSUE THREAD

**Issue by u93** [balena-io-examples/nvidia-x86#3] opened 2022-04-13 16:55 UTC
Hello,

Have you tried the update HostOS flow and is there some guide on steps rebuild the drivers with the new kernel modules?

Reason I ask is that we are trying to integrate this solution into our product, and actions like driver updates work ok, but the moment that we update the Host OS, even after the drivers get rebuilt, is impossible to insert them.

Regards,

**Comment by alanb128** [comment] 2022-04-21 00:03
Hello @u93 I have not tried updating the HostOS since this was published. What version of the OS are you trying to update to? What kind of errors are you getting? I'll see if I can reproduce them.

**Comment by alanb128** [comment] 2022-08-23 03:24
I'm closing this for now, but feel free to reopen if you are still having issues updating the HostOS.

**Closed as completed by alanb128** 2022-08-23 03:24 UTC
